# Site settings
title: The Place of Securasu
email: sephicrash@live.cn
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my place
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://place.securasu.jp" # the base hostname & protocol for your site
twitter_username: 
github_username:  securasu

# Build settings
markdown: kramdown
